services:
    feed-feeder: !reset
    article-feeder: !reset
    news-feeder: !reset
    keyword-matcher: !reset
    raindrop-integration: !reset
    watchtower: !reset
    fullfeedrss:
        ports:
            - '55800:80'
    devcontainer:
        build:
            context: ./golang/
            dockerfile: Dockerfile
            target: devcontainer
        environment:
            - NATS_URL=nats-server
        volumes:
            # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
            # mounts are relative to the first file in the list, which is a level up.
            - .:/workspace:cached

        # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined

        # Overrides default command so things don't shut down after the process ends.
        command: /bin/sh -c "while sleep 1000; do :; done"
