services:
  service:
    image: ghcr.io/heussd/nats-news-analysis/search-mcp-server:latest
    build:
      context: .
      target: search-mcp-server
    env_file:
      - ../.env
    ports:
      - "8000:8000"

